"""
Analyze a public HHS OCR healthcare breach sample.

Usage:
    python scripts/analyze_hhs_breaches.py data/hhs-ocr-breach-sample-2026-05-16.csv --as-of 2026-05-16

The script uses only Python's standard library. It produces a generated
Markdown summary. Repository visuals are generated by tools/generate_portfolio_visuals.py
and checked by tools/visual_quality_check.py.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from collections import Counter, defaultdict
from statistics import median
from pathlib import Path




def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        required = {'covered_entity','state','covered_entity_type','individuals_affected','breach_submission_date','type_of_breach','location_of_breached_information','business_associate_present'}
        if not required.issubset(reader.fieldnames or []):
            raise ValueError('Missing required HHS columns')
        rows = list(reader)
    if any(None in row or any(v is None for v in row.values()) for row in rows):
        raise ValueError("Malformed CSV row width")
    if not rows:
        raise ValueError('HHS input has no rows')
    for i, row in enumerate(rows, 2):
        parse_int(row['individuals_affected'])
        date_text = row['breach_submission_date'].strip()
        try:
            dt.date.fromisoformat(date_text)
        except ValueError:
            dt.datetime.strptime(date_text, '%m/%d/%Y')
        if row['business_associate_present'].strip().lower() not in {'yes','no'}:
            raise ValueError(f'Invalid business associate flag at CSV line {i}')
        if not row['covered_entity'].strip():
            raise ValueError(f'Missing entity at CSV line {i}')
    if len({tuple(sorted(row.items())) for row in rows}) != len(rows):
        raise ValueError('Duplicate complete HHS row')
    return rows


def parse_int(value: str) -> int:
    cleaned = (value or "").replace(",", "").strip()
    if not cleaned or not cleaned.isdecimal():
        raise ValueError('Affected-individual count must be a non-negative integer')
    return int(cleaned)


def counter_by(rows: list[dict[str, str]], field: str) -> Counter[str]:
    return Counter((row.get(field) or "Unknown").strip() or "Unknown" for row in rows)


def affected_by(rows: list[dict[str, str]], field: str) -> dict[str, int]:
    totals: dict[str, int] = defaultdict(int)
    for row in rows:
        key = (row.get(field) or "Unknown").strip() or "Unknown"
        totals[key] += parse_int(row.get("individuals_affected", "0"))
    return dict(totals)


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value).replace("|", "\\|").replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def build_summary(rows: list[dict[str, str]], as_of: dt.date) -> str:
    breach_counts = counter_by(rows, "type_of_breach")
    location_counts = counter_by(rows, "location_of_breached_information")
    entity_counts = counter_by(rows, "covered_entity_type")
    affected_breach = affected_by(rows, "type_of_breach")
    total_affected = sum(parse_int(row.get("individuals_affected", "0")) for row in rows)

    return "\n".join(
        [
            "# HHS OCR Breach Sample Summary",
            "",
            f"Analysis date: {as_of.isoformat()}",
            "",
            "## Sample Snapshot",
            "",
            markdown_table(
                ["Metric", "Value"],
                [
                    ["Sample records", f"{len(rows):,}"],
                    ["Sum of reported affected individuals (not unique people)", f"{total_affected:,}"],
                    ["Median reported affected individuals per record", f"{median(parse_int(r['individuals_affected']) for r in rows):,.1f}"],
                    ["Hacking/IT incident records", f"{breach_counts.get('Hacking/IT Incident', 0):,}"],
                    ["Network Server-only records", f"{location_counts.get('Network Server', 0):,}"],
                    [
                        "Business associate present",
                        f"{sum(1 for row in rows if row.get('business_associate_present', '').strip().lower() == 'yes'):,}",
                    ],
                ],
            ),
            "",
            "## Breach Type Frequency",
            "",
            markdown_table(["Breach type", "Records"], [[key, value] for key, value in breach_counts.most_common()]),
            "",
            "## Affected Individuals By Breach Type",
            "",
            markdown_table(
                ["Breach type", "Affected individuals"],
                [[key, f"{value:,}"] for key, value in sorted(affected_breach.items(), key=lambda item: item[1], reverse=True)],
            ),
            "",
            "## Location Frequency",
            "",
            markdown_table(["Location", "Records"], [[key, value] for key, value in location_counts.most_common()]),
            "",
            "## Entity Type Frequency",
            "",
            markdown_table(["Entity type", "Records"], [[key, value] for key, value in entity_counts.most_common()]),
            "",
            "## Method Note",
            "",
            "This generated summary uses the local dated HHS OCR sample stored in the project data folder. It supports sample description and risk framing, but it is not a HIPAA compliance determination or an assessment of any specific organization's internal controls.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze HHS OCR breach sample data.")
    parser.add_argument("input_csv", type=Path)
    parser.add_argument("--as-of", default=dt.date.today().isoformat())
    parser.add_argument("--output-dir", type=Path, default=Path("outputs"))
    args = parser.parse_args()

    as_of = dt.date.fromisoformat(args.as_of)
    rows = read_rows(args.input_csv)
    suffix = as_of.isoformat()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    (args.output_dir / f"hhs-breach-summary-{suffix}.md").write_text(build_summary(rows, as_of), encoding="utf-8")

    print(f"Rows loaded: {len(rows):,}")
    print(f"Summary written: {args.output_dir / f'hhs-breach-summary-{suffix}.md'}")
    print("Visuals are generated by tools/generate_portfolio_visuals.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
